FROM node:14

WORKDIR /app

# COPY ../../package*.json ./
COPY ../../package*.json ./

RUN npm install

RUN npm install pg

COPY . .

# EXPOSE 5000

# CMD ["node", "start"]
CMD ["npm", "start"]
